services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    container_name: balance_postgres
    environment:
      POSTGRES_DB: balance_service
      POSTGRES_USER: balance_user
      POSTGRES_PASSWORD: balance_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - balance_network
      - microservices_net

  # PHP-FPM контейнер
  app:
    build: .
    container_name: balance_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      KAFKA_BROKER: kafka:9092
      ELASTICSEARCH_HOST: http://elasticsearch:9200
    depends_on:
      - postgres
    networks:
      - balance_network
      - microservices_net

  # Nginx веб-сервер
  nginx:
    image: nginx:alpine
    container_name: balance_nginx
    ports:
      - "8090:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - balance_network
      - microservices_net


volumes:
  postgres_data:

networks:
  balance_network:
    driver: bridge
  microservices_net:
    external: true
